delete http://localhost:3003/api/blogs/69ea13b37cf0743a964be151
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZpbGxlIiwiaWQiOiI2OWViMTY5NDg4MzJlYWJkYTY1ZTNlOTIiLCJpYXQiOjE3NzcwMTQ0NjZ9.RH0vYdeiTaZwxlSI2Am1skvHmH9ZslRovB5eo8oGCow